name = "proxy-embed"
compatibility_date = "2022-07-12"
main = "workers.js"

[[unsafe.bindings]]
name = "ratelimit"
type = "ratelimit"
namespace_id = "1234"
simple = { limit = 100, period = 60 }

[observability]
enabled = true
head_sampling_rate = 1